name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Validate Maven wrapper and cache it
        uses: actions/checkout@v2
        with:
          repository: "maven-wrapper/maven-wrapper"
          path: ".mvn/wrapper"

      - name: Build with Maven
        run: cd backend && ./mvnw clean compile

      - name: Test with Maven
        run: cd backend && ./mvnw test

      - name: Generate Javadoc
        run: cd backend && ./mvnw javadoc:javadoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./backend/target/site/apidocs
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: true
          cname: javadoc.example.com

      - name: Deploy
        run: echo 'deployment succeed' # replace this with your specific deployment command

    # Define steps to build and test your backend
